[package]
name = "fp"
version = "0.1.0"
authors = ["Team Fiberplane"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
reqwest = {version = "0.11.0", features = ["json"]}
serde_yaml = "0.8.17"
toml = "0.5.8"
serde = {version = "1.0.123", features = ["derive"]}
tokio = { version = "1", features = ["full"] }
